Html basics
HappyJuliana/Tekwill_Nice_1 pull request #2
Opened 2023-08-14 20:03 UTC by HappyJuliana

![image](https://github.com/HappyJuliana/Tekwill_Nice_1/assets/128743829/3fd4d731-1870-4a95-bb7f-8a8998152ada)

в следующий раз обещаю чаще коммитить :)
а то в этот раз вышло все до кучи, но было уже поздно что-то менять

2023-08-15 09:38 UTC, IvanCeban requested changes
Some cleanup is required, overall Great job!

2023-08-15 09:38 UTC, IvanCeban commented on index.html
> +    <h3>Why should you learn HTML?
Get used to keep the code always aligned. 
So the opening and closing tags should be on the same column. 
If you have element in 1 line, then opening and closing tags should be in 1 line.

2023-08-15 09:38 UTC, IvanCeban commented on index.html
> +    <h3>Why should you learn HTML?
Remove empty lines.

2023-08-15 09:38 UTC, IvanCeban commented on index.html
> +    <h3>Why should you learn HTML?
The main point of my comments is to keep the code as clean as possible

2023-08-16 12:44 UTC, HappyJuliana commented on index.html
> +    <h3>Why should you learn HTML?
Thanks! I've made some corrections so now the code looks "clean" (as I think)

2023-08-16 12:52 UTC, IvanCeban approved these changes

2023-08-16 18:17 UTC, merged